---
- name: Install certbot
  yum:
    name: certbot
    state: present

- name: Install python3-certbot-nginx
  yum:
    name: python3-certbot-nginx
    state: present

- name: Create acme-challenge directory
  file:
    path: /var/www/letsencrypt/.well-known/acme-challenge
    state: directory
    mode: '0755'

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

- name: Install SSL certificate
  shell: certbot certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}

- name: Write nginx virtualhost-ssl
  template:
    src: nginx-virtualhost-ssl.j2
    dest: /etc/nginx/conf.d/{{ virtualhost_ssl_name }}

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: daily
    job: certbot renew --post-hook "systemctl reload nginx"
  notify:
    - Reload nginx
...